CREATE TABLE `cardAccessLevels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cardId` int NOT NULL,
	`countryCode` varchar(10) NOT NULL,
	`siteId` int NOT NULL,
	`accessLevelId` int NOT NULL,
	`accessLevelName` varchar(255),
	`roomIds` json,
	`validFrom` timestamp,
	`validUntil` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`siportZoneIds` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cardAccessLevels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cardAuditLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cardId` int NOT NULL,
	`operation` enum('created','modified','activated','deactivated','blocked','unblocked','renewed','replaced','access_added','access_removed','access_modified','yaqeen_verified','yaqeen_override','siport_synced','siport_failed') NOT NULL,
	`performedBy` int NOT NULL,
	`performedAt` timestamp NOT NULL DEFAULT (now()),
	`reason` text,
	`previousData` json,
	`newData` json,
	`requestId` int,
	`ipAddress` varchar(45),
	`userAgent` text,
	CONSTRAINT `cardAuditLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cardCompanies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameAr` varchar(255),
	`type` enum('contractor','subcontractor','client') NOT NULL,
	`code` varchar(50),
	`contactPerson` varchar(255),
	`contactEmail` varchar(255),
	`contactPhone` varchar(50),
	`address` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cardCompanies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `magneticCards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cardNumber` varchar(50) NOT NULL,
	`status` enum('pending','active','inactive','blocked','expired') NOT NULL DEFAULT 'pending',
	`blockReason` enum('security_incident','policy_violation','investigation','emergency'),
	`blockType` enum('temporary','permanent'),
	`blockUntil` timestamp,
	`blockedBy` int,
	`blockedAt` timestamp,
	`companyType` enum('centre3','contractor','subcontractor','client') NOT NULL,
	`companyId` int,
	`idType` enum('saudi_id','iqama') NOT NULL,
	`idNumber` varchar(20) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`fullNameAr` varchar(255),
	`birthDate` date NOT NULL,
	`nationality` varchar(100),
	`gender` enum('male','female') NOT NULL,
	`bloodType` varchar(10),
	`mobile` varchar(20) NOT NULL,
	`email` varchar(255),
	`profession` varchar(255),
	`idIssueDate` date,
	`idIssuePlace` varchar(255),
	`idExpiryDate` date NOT NULL,
	`photoUrl` varchar(500),
	`idDocumentUrl` varchar(500),
	`contractUrl` varchar(500),
	`yaqeenVerified` boolean DEFAULT false,
	`yaqeenVerifiedAt` timestamp,
	`yaqeenOverrideBy` int,
	`yaqeenOverrideReason` text,
	`issueDate` timestamp,
	`expiryDate` timestamp,
	`requestId` int,
	`requestedBy` int NOT NULL,
	`approvedBy` int,
	`approvedAt` timestamp,
	`siportCardId` varchar(100),
	`siportSyncedAt` timestamp,
	`siportSyncStatus` enum('pending','synced','failed') DEFAULT 'pending',
	`siportSyncError` text,
	`deactivatedBy` int,
	`deactivatedAt` timestamp,
	`deactivationReason` enum('resignation','termination','contract_ended','security_concern','lost','stolen','damaged','expired','other'),
	`deactivationNotes` text,
	`replacesCardId` int,
	`replacedByCardId` int,
	`lostReportCount` int DEFAULT 0,
	`lastLostReportAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `magneticCards_id` PRIMARY KEY(`id`),
	CONSTRAINT `magneticCards_cardNumber_unique` UNIQUE(`cardNumber`)
);
--> statement-breakpoint
CREATE TABLE `mcmAccessLevels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameAr` varchar(255),
	`description` text,
	`siportZoneMapping` json,
	`requiresApproval` boolean DEFAULT true,
	`maxValidityDays` int DEFAULT 365,
	`allowedCompanyTypes` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mcmAccessLevels_id` PRIMARY KEY(`id`),
	CONSTRAINT `mcmAccessLevels_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `mcmRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestNumber` varchar(50) NOT NULL,
	`operationType` enum('create','modify','deactivate','renew','replace_lost','replace_damaged') NOT NULL,
	`cardId` int,
	`status` enum('draft','pending','approved','rejected','cancelled') NOT NULL DEFAULT 'draft',
	`requestedBy` int NOT NULL,
	`requestedFor` int,
	`requestedAt` timestamp NOT NULL DEFAULT (now()),
	`formData` json,
	`accessLevelsRequested` json,
	`modificationType` enum('add_access','remove_access','change_access'),
	`modificationReason` text,
	`deactivationReason` enum('resignation','termination','contract_ended','security_concern','other'),
	`effectiveDate` timestamp,
	`lostDamagedType` enum('lost','stolen','damaged'),
	`lostDamagedDetails` text,
	`createReplacement` boolean DEFAULT false,
	`workflowInstanceId` int,
	`currentStageId` int,
	`completedAt` timestamp,
	`completedBy` int,
	`resultCardId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mcmRequests_id` PRIMARY KEY(`id`),
	CONSTRAINT `mcmRequests_requestNumber_unique` UNIQUE(`requestNumber`)
);
