CREATE TABLE `formTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`requestType` enum('admin_visit','work_permit','material_entry','tep','mop','escort') NOT NULL,
	`isDefault` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`companyName` varchar(255) DEFAULT 'Centre3',
	`companyNameAr` varchar(255),
	`logoUrl` varchar(500),
	`headerColor` varchar(20) DEFAULT '#6B21A8',
	`footerText` text,
	`footerTextAr` text,
	`footerPhone` varchar(50),
	`footerEmail` varchar(255),
	`footerDepartment` varchar(255),
	`footerDepartmentAr` varchar(255),
	`formTitle` varchar(255) DEFAULT 'Visit Permission',
	`formTitleAr` varchar(255),
	`formSubtitle` varchar(255),
	`formSubtitleAr` varchar(255),
	`fields` json NOT NULL,
	`infoSections` json,
	`safetyRules` json,
	`disclaimerText` text,
	`disclaimerTextAr` text,
	`showQrCode` boolean NOT NULL DEFAULT true,
	`qrCodePosition` enum('top-right','top-left','bottom-right','bottom-left') DEFAULT 'top-right',
	`showWatermark` boolean DEFAULT false,
	`watermarkText` varchar(100),
	`pageSize` enum('a4','letter') DEFAULT 'a4',
	`orientation` enum('portrait','landscape') DEFAULT 'portrait',
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `formTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `generatedForms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` int NOT NULL,
	`templateId` int NOT NULL,
	`qrCodeData` varchar(500) NOT NULL,
	`formData` json NOT NULL,
	`pdfUrl` varchar(500),
	`status` enum('active','expired','revoked') NOT NULL DEFAULT 'active',
	`generatedBy` int,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	`revokedAt` timestamp,
	`revokedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `generatedForms_id` PRIMARY KEY(`id`)
);
