CREATE TABLE `integrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`providerType` varchar(50) NOT NULL,
	`description` text,
	`logoUrl` varchar(500),
	`supportsSms` boolean NOT NULL DEFAULT false,
	`supportsWhatsapp` boolean NOT NULL DEFAULT false,
	`supportsEmail` boolean NOT NULL DEFAULT false,
	`isEnabled` boolean NOT NULL DEFAULT false,
	`isDefault` boolean NOT NULL DEFAULT false,
	`credentials` text,
	`config` text,
	`lastTestedAt` timestamp,
	`lastTestStatus` varchar(50),
	`lastTestError` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `integrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `integrations_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `messageLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`triggerRuleId` int,
	`eventType` varchar(100) NOT NULL,
	`integrationId` int,
	`providerType` varchar(50),
	`channel` enum('sms','whatsapp','email') NOT NULL,
	`templateId` int,
	`recipientPhone` varchar(50),
	`recipientEmail` varchar(255),
	`recipientName` varchar(255),
	`messageBody` text,
	`requestId` int,
	`taskId` int,
	`userId` int,
	`status` enum('pending','sent','delivered','failed','rejected') NOT NULL DEFAULT 'pending',
	`providerMessageId` varchar(255),
	`errorCode` varchar(100),
	`errorMessage` text,
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`retryCount` int NOT NULL DEFAULT 0,
	`maxRetries` int NOT NULL DEFAULT 3,
	`nextRetryAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `messageLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `messageTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`description` text,
	`channel` enum('sms','whatsapp','email') NOT NULL,
	`subject` varchar(500),
	`body` text NOT NULL,
	`bodyAr` text,
	`variables` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `messageTemplates_id` PRIMARY KEY(`id`),
	CONSTRAINT `messageTemplates_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `messageTriggerRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`eventType` varchar(100) NOT NULL,
	`templateId` int NOT NULL,
	`integrationId` int,
	`recipientType` enum('requester','approver','host','visitor','site_manager','custom_field','specific_user','specific_number') NOT NULL,
	`recipientConfig` text,
	`conditions` text,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`siteId` int,
	`requestTypeSlug` varchar(100),
	`priority` int NOT NULL DEFAULT 100,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `messageTriggerRules_id` PRIMARY KEY(`id`)
);
